CREATING AN ARRAY

In [15]:
#importing an array
import array

my_array=array.array('i')
print(my_array)

my_array1 = array.array('i', [1,2,3,4])
print(my_array1)


array('i')
array('i', [1, 2, 3, 4])


In [2]:
#using numpy
import numpy as np
np_array= np.array([], dtype = int)
print(np_array)

np_array1= np.array([1, 2, 3, 4])
print(np_array1)

[]
[1 2 3 4]


INSERTION TO AN ARRAY

In [14]:
print(my_array1)

array('i', [1, 2, 3, 4])


In [16]:
my_array1.insert(0, 6)
print(my_array1)

array('i', [6, 1, 2, 3, 4])


ARRAY TRAVERSAL

the time complexity for traversal is O(n)

In [19]:
from array import *

arr1 = array('i', [1,2,3,4])
arr2 = array('d', [1.3, 1.5, 1.6])

arr1.insert(2,9)
print(arr1)

def traverseArray(array):
    for i in array:
        print(i)

traverseArray(arr1)

array('i', [1, 2, 9, 3, 4])
1
2
9
3
4


ACCESS AN ARRAY IN AN ELEMENT

the time complexity for accessing is O(1)

In [33]:
from array import *

arr1 = array('i', [1, 2, 3, 4, 5, 6])

def accessElement(array, index):
    if index >= len(array):
      print("there is no such index")
    else:
      print(array[index])

accessElement(arr1, 2)

3


SEARCHING AN ELEMENT IN AN ARRAY

the time complexity for searching is O(n) 
and space complexity is O(1)

In [37]:
import array

my_array1 = array.array('i', [1,2,3,4,5])

def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1

print(linear_search(my_array1, 5))

4


DELETING AN ELEMENT FROM AN ARRAY

time complexity will be O(n)
space complexity will be O(1)


In [40]:
from array import *

arr1 = array('i', [1, 2, 3, 4, 5, 6])

arr1.remove(6)

print(arr1)

array('i', [1, 2, 3, 4, 5])


TWO-DIMENSIONAL ARRAY

In [6]:
import numpy as np

twoDArray = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(twoDArray)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
#prints no. of rows
print(len(twoDArray))

#prints no. of columns
print(len(twoDArray[0]))

4
4


INSERTION IN A 2D ARRAY
`#np.insert(array, index, value, axis)`
time complexity for insertion is O(mn) because both rows and columns are affected

In [14]:
print(twoDArray)

#inserting a new row, axis should be 0
newTwoDArray = np.insert(twoDArray, 0, [99,98,97,96], axis = 0)
print(newTwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[99 98 97 96]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
print(twoDArray)

#inserting a new column, axis should be 1
newTwoDArray = np.insert(twoDArray, 0, [99,98,97,96], axis = 1)
print(newTwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[99  1  2  3  4]
 [98  5  6  7  8]
 [97  9 10 11 12]
 [96 13 14 15 16]]


In [20]:
#we can also use the append function, it works similarly. it joins at the end of the code

print(twoDArray)

#inserting a new column, axis should be 1
newTwoDArray = np.append(twoDArray,[[99,98,97,96]], axis = 0)
print(newTwoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [99 98 97 96]]


ACCESSING AN ELEMENT IN A 2D ARRAY

In [23]:
import numpy as np

twoDArray = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(twoDArray)

def accessElementTwoD(array, rowIndex, colIndex):
    if rowIndex >= len(array) or colIndex >= len(array[0]):
        print("there is no such index")
    else:
        print(array[rowIndex][colIndex])


accessElementTwoD(twoDArray, 2, 3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
12


TRAVERSING THROUGH A 2D ARRAY

In [29]:
import numpy as np

twoDArray = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(twoDArray)

def traverseArrayTwoD(array):
    for i in range(len(twoDArray)):
        for j in range(len(twoDArray[0])):
            print(array[i][j])

traverseArrayTwoD(twoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


SEARCHING AN ELEMENT IN A 2D ARRAY

In [33]:
import numpy as np

twoDArray = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(twoDArray)

def searchTwoDArray(array, value):
    for i in range(len(twoDArray)):
        for j in range(len(twoDArray[0])):
            if array[i][j] == value:
                return 'the index of the value is ' + str(i) + " & " + str(j)
    return 'element not found'
            
searchTwoDArray(twoDArray, 12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


'the index of the value is 2 & 3'

DELETION IN 2D ARRAY

In [39]:
import numpy as np

twoDArray = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(twoDArray)

#for rows the axis should be 0, and for columns the axis will be 1
newTDArray = np.delete(twoDArray, 0, axis = 0)
print(newTDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
